### ISSUE TITLE
Orion DEBUG INFO: orion-cli-cli 3.5.4, orion-cli 1.8.26, node v12.16.3, linux x64, exit 1

### ISSUE THREAD

**Issue by ghost** [keshavbhatt/keshavbhatt#1]
so yeah. Torrent download ended with this unexpected error.
DEBUG INFO: orion-cli-cli 3.5.4, orion-cli 1.8.26, node v12.16.3, linux x64, exit 1

**Comment by keshavbhatt** [comment]
Hi, can you email me the hash of torrent you was trying?
